1.16.4 - Add support for Quark's wooden posts
team-abnormals/abnormals-core pull request #64
Opened 2021-01-07 15:49 UTC by EltrutLikes

Follow up to #49 that adds a new class `WoodPostBlock` and a new model file to accommodate the new wooden posts in Quark in addition to removing two unused imports in the `BookshelfBlock` class.

2021-01-07 18:38 UTC, SmellyModder requested changes
A few nitpicks.
You should also add a test wooden post.

2021-01-07 18:38 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/common/blocks/wood/WoodPostBlock.java
> +	public static final BooleanProperty WATERLOGGED = BlockStateProperties.WATERLOGGED;
Why is this public? It's not called externally anywhere.
```suggestion
	private static final BooleanProperty WATERLOGGED = BlockStateProperties.WATERLOGGED;
```

2021-01-07 18:38 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/common/blocks/wood/WoodPostBlock.java
> +	private static final VoxelShape SHAPE = Block.makeCuboidShape(6F, 0F, 6F, 10F, 16F, 10F);
```suggestion
	private static final VoxelShape SHAPE = Block.makeCuboidShape(6.0F, 0.0F, 6.0F, 10.0F, 16.0F, 10.0F);
```

2021-01-07 18:38 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/common/blocks/BookshelfBlock.java
> -import net.minecraft.world.IBlockReader;
Don't include these changes. They have nothing to do with this PR.

2021-01-08 00:37 UTC, EltrutLikes commented
The nitpicks have been fixed and a test post has been added.

2021-01-08 01:53 UTC, SmellyModder approved these changes

2021-01-08 01:53 UTC, merged