[1.16.5] Sign Refactor
team-abnormals/abnormals-core pull request #94
Opened 2021-04-02 18:38 UTC by JacksonPlayz

This PR refactors signs to use the vanilla `WoodType` which allows for the use of the default vanilla sign classes (better compatibility). Custom standing and wall block classes along with a custom tile entity class is still required to use our tile entity so we can register new sign blocks.

I've also backported a change from my previous sign refactor PR which makes `TileEntitySubRegistryHelper#collectBlocks` take in any class instead of one that extends block as `AbnormalsAbstractSignBlock` no longer exists.

2021-04-02 18:48 UTC, SmellyModder requested changes

2021-04-02 18:48 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/AbnormalsCore.java
> +	public static final Set<WoodType> WOOD_TYPES = new HashSet<>();
Not a fan of this field being in `AbnormalsCore`.
A `SignManager` class would be better.

2021-04-02 18:48 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/util/registry/BlockSubRegistryHelper.java
> +		AbnormalsCore.WOOD_TYPES.add(type);
This is not safe during parallel mod loading.
The `HashSet` could become corrupted easily. This is more reason to add a `SignManager` class with threadsafe methods.

2021-04-03 00:49 UTC, SmellyModder requested changes

2021-04-03 00:49 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/api/SignManager.java
> +    public static final Set<WoodType> WOOD_TYPES = new HashSet<>();
```suggestion
    private static final Set<WoodType> WOOD_TYPES = new HashSet<>();
```

2021-04-03 00:49 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/AbnormalsCore.java
> +	public static final Set<WoodType> WOOD_TYPES = new HashSet<>();
This field is still here.

2021-04-03 00:49 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/api/SignManager.java
> +public class SignManager {
```suggestion
public final class SignManager {
```

2021-04-03 00:49 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/util/registry/BlockSubRegistryHelper.java
> +import com.minecraftabnormals.abnormals_core.core.AbnormalsCore;
Unused import.

2021-04-03 01:06 UTC, SmellyModder requested changes

2021-04-03 01:06 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/AbnormalsCore.java
> +import net.minecraft.client.renderer.Atlases;
Unused import.

2021-04-03 01:06 UTC, SmellyModder commented on src/main/java/com/minecraftabnormals/abnormals_core/core/AbnormalsCore.java
> +import net.minecraft.block.WoodType;
Unused import.

2021-04-03 01:14 UTC, JacksonPlayz commented on src/main/java/com/minecraftabnormals/abnormals_core/core/AbnormalsCore.java
> +import net.minecraft.client.renderer.Atlases;
trollge

2021-04-03 01:17 UTC, SmellyModder approved these changes

2021-04-03 01:17 UTC, merged